config/routes.rb
Food::Application.routes.draw do

  resources :shops

  resources :baskets do
    resources :purchases
  end
  
  resources :products

  
  root :to => "baskets#index"

end

app/models/basket.rb
class Basket < ActiveRecord::Base

  belongs_to :shop
  
  has_many :purchases, :extend => MergePurchasesExtension
  has_many :products, :through => :purchases, :uniq => true
  has_many :savings,  :through => :purchases, :uniq => true

  has_many :bills
  accepts_nested_attributes_for :bills
    
  before_validation :set_shop_date
  before_validation :ensure_billed
  
  validates_presence_of :shop
  validates_presence_of :shop_date
    
  after_create :create_primary_bill
  
  def shop_date_string
    shop_date.nil? ? '' : shop_date.strftime('%A, %d %B %y')
  end
    
  def cost
    purchases.map(&:cost).sum
  end
  
  private
  
  def set_shop_date
    self.shop_date ||= Date.today.to_time
  end
  
  def create_primary_bill
    bills.create!(:proportion => 100)
  end
  
  def ensure_billed
    if (100.0 - bills.map(&:proportion).sum).abs > 0.5
      bills.each { |bill| bill.proportion = (100.0 / bills.length) } 
    else
      bills.last.proportion = 100.0 - (bills - [ bills.last ]).map(&:proportion).sum
    end
  end
  
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :basket
    
  after_initialize :set_defaults, :if => :new_record?
  
  private
  
  def set_defaults
    self.proportion ||= 0
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :ean
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  before_validation :format_ean
  validates_length_of :ean, :is => 13, :allow_blank => true

  
  has_many :purchases, :dependent => :destroy
  has_many :baskets, :through => :purchases, :uniq => true
  
  def self.find_for_autocomplete(query)
    where('ean like ? or name like ?', "#{query}%", "%#{query}%")
  end
  
  def self.find_or_create_from_params(params)
    existing = find_by_name(params[:name])
    if existing
      existing
    else
      create!(:name => params[:name], :ean => params[:ean])
    end
  end
  
  def purchase_count
    purchases.map(&:quantity).sum
  end
  
  def total_spending
    purchases.map(&:cost).sum
  end
  
  private
  
  def format_ean
    self.ean = ean.blank? ? nil : ean.to_s.gsub(/[^\d]/, '')
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :product
  belongs_to :basket
    
  has_one :saving  
  accepts_nested_attributes_for :saving
    
  validates_presence_of :quantity
  validates_presence_of :unit_price_in_pence
  validates_presence_of :product_id
  validates_presence_of :basket_id
  
  validates_numericality_of :quantity
  validates_numericality_of :unit_price_in_pence
  
  # Track whether this purchase was :created 
  # or :updated or neither (nil).  
  attr_accessor :creation_status
  
  after_save :delete_if_zero_quantity
    
  def merge_with(purchase)
    self.quantity += purchase.quantity
    self
  end
    
  def cost
    unit_price * quantity rescue 0
  end
  
  def unit_price
    unit_price_in_pence ? (unit_price_in_pence.to_f / 100).round(2) : nil
  end
  
  def unit_price=(price_in_pounds)
    write_attribute(:unit_price_in_pence, (price_in_pounds.to_f.round(2) * 100).round(0).to_i)
  end
  
  private
  
  def delete_if_zero_quantity
    delete if quantity.zero?
  end
end

app/models/saving.rb
class Saving < ActiveRecord::Base
  SAVING_TYPES = [
    'buy_one_get_one_free'
  ]
  
  belongs_to :purchase
  
  before_save :set_amount
  
  def amount
    amount_in_pence ? (amount_in_pence.to_f / 100).round(2) : nil
  end
  
  def amount=(amount_in_pounds)
    write_attribute(:amount_in_pence, (amount_in_pounds.to_f.round(2) * 100).round(0).to_i)
  end
  
  private
  
  def set_amount
    if SAVING_TYPES.include?(saving_type)
      self.amount = self.send(saving_type.to_sym) 
    end
  end
  
  def buy_one_get_one_free
    Rails.logger.info("************* #{purchase_id}")
    purchase.quantity.div(2) * purchase.unit_price
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :baskets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :simulate_xhr
  
  private
  
  def simulate_xhr
    sleep(1) if request.xhr? && request.post? && Rails.env.development?
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def index
    @baskets = Basket.all
  end

  def new
    @basket = Basket.new
  end
  
  def create
    @basket = Basket.new(params[:basket])
    if @basket.save
      redirect_to @basket
    else
      flash[:error] = "Basket not valid"
      render 'new'
    end
  end

  def update
    @basket = Basket.find(params[:id])
    if @basket.update_attributes(params[:basket])
      redirect_to @basket
    else
      flash[:error] = "Error updating basket"
      render 'show'
    end
  end

  def show
    @basket = Basket.find(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :html, :json
    
  def index
    @products = if params[:query].blank?
      Product.includes(:purchases).all
    else
      Product.limit(10).find_for_autocomplete(params[:query])
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => view_context.autocomplete_data_for(@products) }
    end
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end
  
  def update
  end
  
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path
    else
      flash[:error] = "Failed to delete product"
    end
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  respond_to :html, :js
  
  before_filter :find_basket
  
  def create
    product = Product.find_or_create_from_params(params[:product])
    purchase = @basket.purchases.create_or_update(params[:purchase].merge(:product_id => product.id))
    
    if (product.new_record? || purchase.new_record?) && !request.xhr?
      flash[:error] = 'Error saving!'
    else
      flash[:notice] = 'Saved!'
    end
    
    respond_to do |format|
      format.html { redirect_to @basket }
      format.js { render @basket }
    end
  end
  
  private
  
  def find_basket
    @basket = Basket.find(params[:basket_id])
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(params[:shop])
    if @shop.save
      flash[:notice] = "'#{@shop.name}' created."
      redirect_to root_url
    else
      flash[:error] = "Invalid shop"
      render :action => 'new'
    end
  end

end

app/helpers/application_helper.rb
#coding: utf-8

module ApplicationHelper
  def format_price(price, include_unit = true)
    format_string = include_unit ? '£%n' : '%n'
    number_to_currency(price, :precision => 2, :format => format_string)
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper

  def tagged_purchases_for(basket)
    purchases = basket.purchases.order('updated_at desc').reject(&:new_record?)
    
    log = basket.purchases.update_log
    
    purchases.each do |purchase|
      status = log[purchase.id]
      purchase.creation_status = status if status
    end
    
    purchases
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def ean_for(product)
    if product.ean.blank?
      'x xxxxxx xxxxxx'
    else
      ean = product.ean.to_s
      sprintf('%s %s %s', ean[0,1], ean[1,6], ean[7,6])
    end
  end
  
  def autocomplete_data_for(products)
    [].tap do |array|
      products.each do |product|
        array << { 'product' => { :name => product.name, :ean => ean_for(product) }}
      end
    end
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def div_for_purchase(purchase, options = {}, &block)
    status = purchase.creation_status
    (options[:class] ||= '') << status.to_s if status
    
    div_for(purchase, options, &block)
  end
  
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/baskets/_basket.html.erb
<% basket_purchases = tagged_purchases_for(basket) %>

<div id="existing_purchases" border="0" cellspacing="0">
  <% basket_purchases.each do |purchase| %>
    <%= div_for_purchase(purchase) do %>
      <span class="purchase-quantity">
        <%= purchase.quantity %>
      </span>
      <span class="product-name">
        <%= purchase.product.name %>
        @ <%= format_price(purchase.unit_price, false) %>
      </span>
      <span class="purchase-cost">
        <%= format_price(purchase.cost, false) %>
      </span>
      <span class="purchase-controls">
        <%= link_to 'go', purchase.product %> |
        <%= link_to 'edit' %>
      </span>
      
      <% if purchase.saving %>
        <%= div_for(purchase.saving) do %>
          <span class="purchase-quantity">&nbsp;</span>
          <span class="product-name">
            &nbsp;&nbsp; - <%= purchase.saving.saving_type.humanize %>
          </span>
          <span class="purchase-cost"><%= format_price(-purchase.saving.amount) %></span>
        <% end %>
      <% end %>
      
      <div style="clear:both"></div>
    <% end %>
  <% end %>
</div>  

<% if basket_purchases.any? %>
  <div id="basket_totals">
    <span class="purchase-quantity">&nbsp;</span>
    <span class="product-name">&nbsp;</span>
    <span class="purchase-cost basket-cost">
      <%= format_price(basket.cost) %>
    </span>
  </div>
<% end %>

app/views/baskets/_basket_header.html.erb
<div>
  <h1>
    <%= basket_header.shop_date_string %>
    <span class="grey"> - <%= basket_header.shop.name %></span>
  </h1>
</div>

app/views/baskets/edit.html.erb
<h1>Baskets#edit</h1>
<p>Find me in app/views/baskets/edit.html.erb</p>

app/views/baskets/index.html.erb
<% for basket in @baskets do %>

  <%= render :partial => "basket_header", :object => basket %>
  <%= link_to "go...", basket %>
  <hr />
<% end %>

<%= link_to "New Basket", new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket:</h1>

<%= form_for @basket do |form| %>
  <p>
    <%= form.label :shop_id, "Shop" %>
    <%= select :basket, :shop_id, Shop.all.map { |shop| [ shop.name, shop.id ] } %>
    (<%= link_to 'new', new_shop_path %>)
  </p>

  <p>
    <%= form.label :shop_date, "Shop Date" %>
    <%= date_select :basket, :shop_date, :use_month_numbers => true %> 
  </p>
  
  <%= form.submit "Create", :disable_with => 'Creating...' %>
<% end %>

app/views/baskets/show.html.erb
<%= render :partial => 'basket_header', :object => @basket %>

<em>Billing data hidden</em>
<!-- <%= form_for @basket do |basket_form| %>
  <%= render :partial => 'bills/pie_bills', :object => @basket.bills, :locals => { :form => basket_form }  %>
  <%= basket_form.submit 'Update bills' %>
<% end %> -->

<%= form_for [@basket, @basket.purchases.build], :html => { :autocomplete => 'off' } do |form| %>
  
  <span class="progress" style="display:none;"></span>

  <table class="new-product-wrapper">
    <tr>
      <td><%= form.text_field :quantity, :placeholder => 'No.' %></td>
      <td class="product-wrapper">
        <div id="product-cassette">
          <%= fields_for :product do |product_form| %>
            <%= product_form.text_field :name, :placeholder => 'Product Name' %>
            <%= product_form.text_field :ean, :placeholder => 'Product EAN', :tabindex => -1 %>
          <% end %>
        </div>    
      </td>
      <td>
        <span class="grey">£</span> 
        <%= form.text_field :unit_price, :placeholder => '(each)' %>
      </td>
    </tr>
  </table>
    
  <div style="display:none" class="multibuy-options">
    <% form.object.build_saving %>
    <%= form.fields_for :saving do |saving_form| %>
            
      <%= Saving::SAVING_TYPES.each do |type| %>
        <%= saving_form.radio_button :saving_type, type %>
      <% end %>
      
    <% end %>
  </div>
      
<% end %>

<div id="basket"><%= render @basket %></div>

app/views/bills/_bill.html.erb
<div>
  <div style="width: 100px; height: 1em;border: 1px solid black;">
    <div style="width: <%= bill.proportion %>px; height: 1em; background-color: red">
      <span><%= bill.proportion %>%</span>
    </div>
  </div>
</div>

app/views/bills/_bills.html.erb
<%# render bills %>

<canvas id="pie_controller" width="200" height="200">
  Polite notice: your browser sucks.
</canvas>

<%= form.fields_for :bills do |bills_form| %>
  <%= bills_form.hidden_field :proportion %>
<% end %>

<% segments = [] %>
<% bills.each_with_index do |bill, index|  
  skew = segments.any? ? segments.last[:bounds][:max] : -Math::PI
  
  segments << {
    :bill => bill.id,
    :fieldId => "#basket_bills_attributes_#{index}_proportion",
    :proportion => bill.proportion,
    :originalProportion => bill.proportion,
    :bounds => { :min => 0, :max => 0 }
    # :bounds => { :min => skew, :max => skew + (Math::PI * bill.proportion.to_f / 50) }
  }
end %>

<script type="text/javascript" charset="utf-8">

  var V = {
    init: function(x, y) {
      return { x: x, y: y };
    },
    
    sub: function(v1, v2) {
      return V.init(v1.x-v2.x, v1.y-v2.y);
    },
    
    magnitude: function(v) {
      return Math.sqrt( V.dot(v, v) );
    },
    
    dot: function(v1, v2) {
      return v1.x*v2.x + v1.y*v2.y;
    },
    
    cross: function(v1, v2) {
      return v1.x*v2.y - v1.y*v2.x
    },
    
    scale: function(v, k) {
      return { x: v.x*k, y: v.y*k };
    },
    
    normalize: function(v) {
      return V.scale(v, 1 / V.magnitude(v));
    },
    
    angle: function(v1, v2) {
      return Math.atan2( V.cross(v1, v2), V.dot(v1, v2) ) % (2*Math.PI);
    }
  };

  //get a reference to the canvas
  var ctx = $('#pie_controller')[0].getContext("2d");
  
  var mouseDownOver;
  var mouse = {
    p: V.init(0, 0),
    d: V.init(0, 0)
  };
  
  
  $(ctx.canvas).mousedown(function(e){        
    mouse.p.x = e.pageX - $(this).offset().left,
    mouse.p.y = e.pageY - $(this).offset().top;
    
    var vector = { x: mouse.p.x - 100, y: 100 - mouse.p.y };
    
    // var angleFromO = V.angle(vector, V.init(0, -1));
    var angleFromO = V.angle(vector, V.init(1, 0));
    var matchedIndex;
    
    for(i=0; i < segments.length; i++) {
      if ((angleFromO > segments[i].bounds.min) && (angleFromO < segments[i].bounds.max)) {
        matchedIndex = i;
        break;
      };
    };
    
    mouseDownOver = segments[matchedIndex];
  });
   
  $(ctx.canvas).mouseup(function(e){
    mouseDownOver = null;
    
    $.each(segments, function(index) {
      this.originalProportion = this.proportion;
      $(this.fieldId).val(this.originalProportion);
    });
  })

  $(ctx.canvas).mousemove(function(e) {
    mouse.d.x = e.pageX - $(this).offset().left;
    mouse.d.y = e.pageY - $(this).offset().top;
    
    var mag = V.magnitude(V.sub(mouse.d, V.init(100, 100)));
    mag *= 3;
    if (mouseDownOver) {         
      mouseDownOver.proportion = mouseDownOver.originalProportion*(mag / 100);
       
      var otherSegments = $(segments).reject(function() {
        return this == mouseDownOver
      });
      
      var increment = mouseDownOver.proportion - mouseDownOver.originalProportion;
      
      $.each(otherSegments, function(index) {
        this.proportion = Math.max(1, this.originalProportion - (increment / otherSegments.length));
      });
    }
  });
   
  
  var angle = 0;
  var segments = $.parseJSON('<%= ActiveSupport::JSON.encode(segments).html_safe %>');
  var colors = [ 'red', 'green', 'yellow', 'blue', 'orange' ];
  
  ctx.translate(100, 100);
  
  setInterval(function(){
     ctx.clearRect(-100, -100, 200, 200);    
     ctx.save()
     ctx.rotate(angle += 0.0);

     for(i=0; i < segments.length; i++) {
       
       var skew = (i>0 ? segments[i-1].bounds.max : -Math.PI);
       segments[i].bounds.min = skew;
       segments[i].bounds.max = skew + (Math.PI*segments[i].proportion / 50) ;
       
       ctx.beginPath()
       ctx.moveTo(0, 0);
       ctx.arc(0, 0, 80, segments[i].bounds.min, segments[i].bounds.max, false); 
       ctx.closePath()
       ctx.fillStyle = colors[i % colors.length];
       ctx.fill();      
     }

     ctx.restore()

   }, 30);
     
</script>

app/views/bills/_pie_bills.html.erb
<%# render bills %>

<canvas id="pie_controller" width="400" height="400">
  Polite notice: your browser sucks.
</canvas>

<%= form.fields_for :bills do |bills_form| %>
  <%= bills_form.hidden_field :proportion %>
<% end %>

<a id="pie_equalise" href="#">Equalise</a>

<% segments = [] %>
<% pie_bills.each_with_index do |bill, index|  
  skew = segments.any? ? segments.last[:bounds][:max] : -Math::PI
  
  segments << {
    :bill => bill.id,
    :fieldId => "#basket_bills_attributes_#{index}_proportion",
    :proportion => bill.proportion,
    :originalProportion => bill.proportion,
    :bounds => { :min => 0, :max => 0 }
    # :bounds => { :min => skew, :max => skew + (Math::PI * bill.proportion.to_f / 50) }
  }
end %>

<script type="text/javascript" charset="utf-8">

  var V = {
    init: function(x, y) {
      return { x: x, y: y };
    },
    
    sub: function(v1, v2) {
      return V.init(v1.x-v2.x, v1.y-v2.y);
    },
    
    magnitude: function(v) {
      return Math.sqrt( V.dot(v, v) );
    },
    
    dot: function(v1, v2) {
      return v1.x*v2.x + v1.y*v2.y;
    },
    
    cross: function(v1, v2) {
      return v1.x*v2.y - v1.y*v2.x
    },
    
    scale: function(v, k) {
      return { x: v.x*k, y: v.y*k };
    },
    
    normalize: function(v) {
      return V.scale(v, 1 / V.magnitude(v));
    },
    
    angle: function(v1, v2) {
      return Math.atan2( V.cross(v1, v2), V.dot(v1, v2) ) % (2*Math.PI);
    }
  };

  var ctx = $('#pie_controller')[0].getContext("2d");
  
  var mouseDownOver;
  var originalProportion;
  var mouse = {
    p: V.init(0, 0),
    d: V.init(0, 0)
  };
  
  
  $(ctx.canvas).mousedown(function(e){        
    mouse.p.x = e.pageX - $(this).offset().left,
    mouse.p.y = e.pageY - $(this).offset().top;
    
    var vector = { x: mouse.p.x - 200, y: 200 - mouse.p.y };
    
    // var angleFromO = V.angle(vector, V.init(0, -1));
    var angleFromO = V.angle(vector, V.init(1, 0));
    var matchedIndex;
    
    for(i=0; i < segments.length; i++) {
      if ((angleFromO > segments[i].bounds.min) && (angleFromO < segments[i].bounds.max)) {
        matchedIndex = i;
        break;
      };
    };
    
    // console.log(colors[matchedIndex % colors.length])
    
    mouseDownOver = segments[matchedIndex];
    originalProportion = mouseDownOver.originalProportion;
  });
   
  $(ctx.canvas).mouseup(function(e){
    mouseDownOver = null;
    
    $.each(segments, function(index) {
      this.originalProportion = this.proportion;
      $(this.fieldId).val(this.originalProportion);
    });
    
    $(ctx.canvas).closest('form').submit()
  });
  
  $('#pie_equalise').click(function(e) {    
    $.each(segments, function(index) {
      this.proportion = 100/segments.length;
      this.originalProportion = this.proportion;
      $(this.fieldId).val(this.originalProportion);
    });
    
    e.preventDefault();
  });

  $(ctx.canvas).mousemove(function(e) {
    if (mouseDownOver) {         
      mouse.d.x = e.pageX - $(this).offset().left;
      mouse.d.y = e.pageY - $(this).offset().top;

      var otherSegments = $(segments).reject(function() { return this == mouseDownOver }),
          currentDistToO = V.magnitude(V.sub(mouse.d, V.init(200, 200))),
          initialDistToO = V.magnitude(V.sub(mouse.p, V.init(200, 200))),
          newProportion;
    
      // What is our new proportion?
      if (currentDistToO < initialDistToO) {
        newProportion = originalProportion * currentDistToO / initialDistToO;
      } else {
        newProportion = originalProportion + (currentDistToO - initialDistToO);
      }
      
      var bound = function(value) {
        return Math.max(1, Math.min(100 - otherSegments.length, value))
      }

      mouseDownOver.proportion = bound(newProportion);
      
      $.each(otherSegments, function(index) {                      
        this.proportion = bound((100 - mouseDownOver.proportion) * this.originalProportion / 100);
      });
      
      // Distribute any rounding error amoung the other segments:
      var roundingError = (100 - $(segments).map(function() { return this.proportion }).sum());
      $.each(otherSegments, function(index) { this.proportion += (roundingError / otherSegments.length) });
    }
  });
   
  
  var angle = 0;
  var segments = $.parseJSON('<%= ActiveSupport::JSON.encode(segments).html_safe %>');
  var colors = [ 'red', 'green', 'yellow', 'blue', 'orange' ];
  
  ctx.translate(200, 200);
  
  setInterval(function(){    
    ctx.clearRect(-200, -200, 400, 400);    
    ctx.save()
    ctx.rotate(angle += 0.0);
    
    for(i=0; i < segments.length; i++) { 
      var skew = (i>0 ? segments[i-1].bounds.max : -Math.PI);
      segments[i].bounds.min = skew;
      segments[i].bounds.max = skew + (Math.PI*segments[i].proportion / 50) ;
      
      ctx.beginPath()
      ctx.moveTo(0, 0);
      ctx.arc(0, 0, 160, segments[i].bounds.min, segments[i].bounds.max, false); 
      ctx.closePath()
      ctx.fillStyle = colors[i % colors.length];
      ctx.fill();      
    }
    
    ctx.restore()  
  }, 30);
     
</script>

app/views/layouts/_header.html.erb
<%= link_to "Food App", root_url %> (<%= Rails.env %>)

<div style="float:left;">
  <% flash.each do |level, message| %>
    <span class="<%= level %>"><%= message %></span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
  <%= render :partial => 'layouts/header' %>
</div>

<div id="content">
  <%= yield %>
</div>

</body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<table>
  <tr><th></th><th>Name</th><th>EAN</th></tr>
  
  <% for product in @products.sort_by(&:purchase_count).reverse do %>
    <tr><td><%= product.purchase_count %></td><td><%= link_to product.name, product %></td><td><%= product.ean %></td></tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product do |f| %>
  <p>
    <%= f.label :name, "Product Name" %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :ean, "Product EAN" %>
    <%= f.text_field :ean %>
  </p>
  
  <%= f.submit "Create", :disable_with => 'Creating...' %>
<% end %>

app/views/products/show.html.erb
<p class="right" style="color:red">
  <%= link_to 'delete', @product, :method => :delete, :confirm => 'Are you sure?' %>
</p>

<h1>
  <%= @product.name %>
  <code>(<%= @product.ean || 'No EAN' %>)</code>
</h1>
<hr />

<p>You have bought <%= @product.purchase_count %> of these in total, from <%= pluralize(@product.baskets.length, 'shopping trip') %>.</p>
<p>Total spending: <%= format_price(@product.total_spending) %></p>
<p>Min paid: <%= format_price @product.purchases.reorder('unit_price_in_pence').first.try(:unit_price) %></p>
<p>Max paid: <%= format_price @product.purchases.reorder('unit_price_in_pence desc').first.try(:unit_price) %></p>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= form_for @shop do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Create" %>
<% end %>